### ISSUE TITLE
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

### ISSUE THREAD

**Issue by Srikiranrao** [ros-industrial/easy_perception_deployment#22] opened 2021-06-18 08:00 UTC
Hi @cardboardcode 
While training for new data we faced the following issue:
![image](https://user-images.githubusercontent.com/43459203/122527735-3038fe00-d04e-11eb-8cb0-24ebaf759f42.png)

The current numpy version in `p3_exporter` conda env is 1.20.3. May I know how to solve this issue.

**Comment by cardboardcode** [comment] 2021-06-18 08:06
Hi @Srikiranrao, this error is caused by the wrong **numpy** version used. I can address this in a hot fix.

For now, please ensure your **numpy** version is `1.19.2`. To do so, you can try the following commands:
```bash
conda activate p3_exporter
pip install numpy==1.19.2
```
Then run the training sequence again from EPD GUI.

**Comment by Srikiranrao** [comment] 2021-06-18 09:25
@cardboardcode 
Downgraded the conda environment 
![image](https://user-images.githubusercontent.com/43459203/122536431-17811600-d057-11eb-9ebb-01d39a5fe527.png)

But still the same issue.

![image](https://user-images.githubusercontent.com/43459203/122536199-db4db580-d056-11eb-916f-b0aea46099cc.png)

**Comment by cardboardcode** [comment] 2021-06-18 09:32
Try uninstall `numpy` and installing again. I am referencing this [solution](https://stackoverflow.com/a/65443366).

```bash
conda activate p3_exporter
pip uninstall numpy
pip install numpy==1.19.3
```

Please ensure that the new numpy installation reflects that `1.19.3`. There are times where this error is due to the wrong PythonPath set on a workstation. 
```bash
pip freeze | grep numpy
```

**Comment by cardboardcode** [comment] 2021-06-18 09:40
If that still does not work, then you can try this:

Add the following line above **line 27** of the file `easy_perception_deployment/easy_perception_deployment/gui/trainer/exporter_files/scripts/install_p3exporter.bash`. [Click here](https://github.com/ros-industrial/easy_perception_deployment/blob/3e0ee1e680ce2d7a937ca3e45983435ed8c05449/easy_perception_deployment/gui/trainer/exporter_files/scripts/install_p3exporter.bash#L27) for the file.
```bash
pip3 install numpy==1.19.2
```
Then remove the `p3_exporter` conda environment you currently have with this command:
```bash
conda env remove --name p3_exporter
```
Then run your training sequence again.

**Comment by cardboardcode** [comment] 2021-06-18 10:28
Verified that this error is reproducible with the latest version of **easy_perception_deployment**.

Will work on a hot fix and do a patch shortly.

**Comment by cardboardcode** [comment] 2021-06-18 11:15
@Srikiranrao 
Feel free to reopen this issue if you are still facing this same issue. 

Closing.

**Closed by cardboardcode** 2021-06-18 11:15 UTC
Labels: bug

**Comment by Srikiranrao** [comment] 2021-06-21 06:31
@cardboardcode 
Thanks, the issue was resolved.
