### ISSUE TITLE
No output from topic /processor/epd_localize_output

### ISSUE THREAD

**Issue by Srikiranrao** [ros-industrial/easy_perception_deployment#15] opened 2021-04-09 09:32 UTC
Hi ROS-I team,
I have deployed the localisation as shown. It can output the image msg in /processor/output. However, there is no output from /processor/epd_localize_output. Same issue for the following topic:
/processor/epd_p1_output
/processor/epd_p2_output
/processor/epd_p3_output
![Screenshot from 2021-04-09 17-28-13](https://user-images.githubusercontent.com/43459203/114160391-717ba600-9959-11eb-88b3-673ee4ea8a7e.png)

**Comment by cardboardcode** [comment] 2021-04-13 05:41
It looks like you are currently on the "Visualize" mode. To view outputs on the `/processor/epd_localize_output`, ensure that you can selected the "Action" mode under the EPD's Deploy Graphical User Interface(GUI).

**Comment by Dcrypt** [comment] 2021-04-14 09:26
Hi, I have changed to Action mode. However, there is an error when running the grasp_planning node from EMD or when echoing from topic /processor/epd_localize_output. The terminal does not show any OBJ detection values, except FPS value. The showimage shown is from image_raw to ensure the object is within camera's view

![Screenshot from 2021-04-14 17-14-25](https://user-images.githubusercontent.com/62248071/114687091-f98cf180-9d45-11eb-9a67-ee917475172d.png)

**Comment by cardboardcode** [comment] 2021-04-14 10:02
@Dcrypt  
> The terminal does not show any OBJ detection values, except FPS value.

This is **expected** behaviour. So no worries there. Users are meant to view the localization results via `ros2 topic ehco /processor/epd_localize_output` under **Action** mode.

> Error: terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException' what(): Not enough memory in the buffer stream

This is **unexpected** behaviour. If it is okay, **please show the terminal output** after running the following command:
```bash
nvidia-smi
```
You should get a result similar to the output below:
```txt
Wed Apr 14 17:57:54 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   42C    P0    29W / 120W |    556MiB /  6075MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1208      G   /usr/lib/xorg/Xorg                            35MiB |
|    0      2336      G   /usr/lib/xorg/Xorg                           287MiB |
|    0      2468      G   /usr/bin/gnome-shell                         121MiB |
|    0      4276      G   /usr/lib/firefox/firefox                       1MiB |
|    0     10662      G   /usr/lib/firefox/firefox                       1MiB |
|    0     13304      G   /usr/lib/firefox/firefox                       1MiB |
|    0     18048      G   ...SitePerProcess --gpu-preferences=IAAAAA    94MiB |
+-----------------------------------------------------------------------------+

```
If **more information of the GPU you are using can be provided**, it would be useful in helping to deduce the cause of this error.

**Comment by cardboardcode** [comment] 2021-04-14 10:13
@Dcrypt 
Also, you can have a look at this external issue under **eProsima** to have a better understanding of the error in question:

https://github.com/ros2/rmw_fastrtps/issues/191#issuecomment-374157667

**Comment by Dcrypt** [comment] 2021-04-15 03:04
`Thu Apr 15 11:03:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:01:00.0  On |                  N/A |
| 52%   49C    P0    31W / 105W |   1760MiB /  8111MiB |     72%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1128      G   /usr/lib/xorg/Xorg                 39MiB |
|    0   N/A  N/A      1859      G   /usr/lib/xorg/Xorg                100MiB |
|    0   N/A  N/A      1997      G   /usr/bin/gnome-shell              106MiB |
|    0   N/A  N/A      6370      G   gnome-control-center                2MiB |
|    0   N/A  N/A     13744      C   ...tion_deployment/processor     1501MiB |
+-----------------------------------------------------------------------------+
`

**Comment by Dcrypt** [comment] 2021-04-15 06:32
I managed to echo from the topic when I open new terminal and source /opt/ros/foxy/setup.bash and epd_msgs only. Once I source the EMD workspace, the NotEnoughMemoryException will appear for both topic echo and grasp_planning_node.

**Comment by cardboardcode** [comment] 2021-04-15 06:40
Hmm... Interesting. Noted. 

@Dcrypt Thank you for reporting this issue and its solution. 

Closing issue.

## Solution
1. Open new terminal.
2. Source ROS2 Foxy: `source /opt/ros/foxy/setup.bash`
3. Source epd_msgs: `source easy_perception_deployment/epd_msgs/install/setup.bash`
#### Do not source EMD workspace.

**Closed by cardboardcode** 2021-04-15 06:40 UTC
